### ISSUE TITLE
How to judge the convergence

### ISSUE THREAD

**Issue by ghost** [Kaixhin/imitation-learning#8]
Hello!

Thanks so much for sharing the code!

I am new at inverse reinforcement learning. Now I am trying to apply AIRL and GAIL to a customized environment without knowing anything about the reward function. So are there any metrics that can be used to judge the convergence except for rewards?

Thanks ;).

**Comment by Kaixhin** [comment]
Yes, although this is difficult, [Hyperparameter Selection for Imitation Learning](https://arxiv.org/abs/2105.12034) proposes some.
